[general]
import = [
    "~/.config/alacritty/catppuccin/catppuccin-mocha.toml"
]

[window]
title = ""
dynamic_title = false
padding = { x = 8, y = 12 }
option_as_alt = "Both"
decorations = "Buttonless"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"
